service: rss-react
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev

functions:
  product:
    handler: handlers/index.handler
    events:
      - httpApi:
          path: /
          method: get
  products:
    handler: handlers/products.handler
    events:
      - httpApi:
          path: /products
          method: get

